"""add_country_and_metadata_columns

Revision ID: 150ac3b2a120
Revises: b6ce6772e57d
Create Date: 2026-07-05 15:25:34.687800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150ac3b2a120'
down_revision: Union[str, None] = 'b6ce6772e57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('grants', sa.Column('funding_currency', sa.String(length=10), nullable=True))
    op.add_column('grants', sa.Column('eligibility_country', sa.String(length=255), nullable=True))
    op.add_column('grants', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_grants_country'), 'grants', ['country'], unique=False)
    op.create_index(op.f('ix_grants_eligibility_country'), 'grants', ['eligibility_country'], unique=False)
    op.create_index(op.f('ix_grants_source_type'), 'grants', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grants_source_type'), table_name='grants')
    op.drop_index(op.f('ix_grants_eligibility_country'), table_name='grants')
    op.drop_index(op.f('ix_grants_country'), table_name='grants')
    op.drop_column('grants', 'source_type')
    op.drop_column('grants', 'eligibility_country')
    op.drop_column('grants', 'funding_currency')
    op.drop_column('grants', 'country')
    # ### end Alembic commands ###
